//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitHubNotifier.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitHubNotifier.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   You were assigned to the issue. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AssignText {
            get {
                return ResourceManager.GetString("AssignText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You created the thread. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AuthorText {
            get {
                return ResourceManager.GetString("AuthorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You commented on the thread. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommentText {
            get {
                return ResourceManager.GetString("CommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You accepted an invitation to contribute to the repository. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvitationText {
            get {
                return ResourceManager.GetString("InvitationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You subscribed to the thread (via an issue or pull request). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ManualText {
            get {
                return ResourceManager.GetString("ManualText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You were specifically @mentioned in the content. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MentionText {
            get {
                return ResourceManager.GetString("MentionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Request timed out or DNS faild. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NetworkErrorText {
            get {
                return ResourceManager.GetString("NetworkErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please check the access information to GitHub. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationErrorText {
            get {
                return ResourceManager.GetString("NotificationErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to get notifications. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationErrorTitle {
            get {
                return ResourceManager.GetString("NotificationErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Icon NotifyIconBlack {
            get {
                object obj = ResourceManager.GetObject("NotifyIconBlack", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Icon NotifyIconWhite {
            get {
                object obj = ResourceManager.GetObject("NotifyIconWhite", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Access to notifications is not allowed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PermissionErrorText {
            get {
                return ResourceManager.GetString("PermissionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You, or a team you&apos;re a member of, were requested to review a pull request. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReviewRequestedText {
            get {
                return ResourceManager.GetString("ReviewRequestedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GitHub discovered a security vulnerability in your repository. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SecurityAlertText {
            get {
                return ResourceManager.GetString("SecurityAlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It was not an GitHub server. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ServerErrorText {
            get {
                return ResourceManager.GetString("ServerErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You changed the thread state. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StateChangeText {
            get {
                return ResourceManager.GetString("StateChangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You&apos;re watching the repository. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SubscribedText {
            get {
                return ResourceManager.GetString("SubscribedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You were on a team that was mentioned. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TeamMentionText {
            get {
                return ResourceManager.GetString("TeamMentionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It was invalid token. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TokenErrorText {
            get {
                return ResourceManager.GetString("TokenErrorText", resourceCulture);
            }
        }
    }
}
